name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 체크아웃 도구 최신화 (v3 -> v4)
    - uses: actions/checkout@v4

    # 파이썬 세팅 도구 최신화 (v4 -> v5)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pandas pyqt5 matplotlib openpyxl pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile --name="DQ_Checker" --clean dq_app.py

    # [핵심 수정] 업로드 도구 최신화 (v3 -> v4)
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DQ_Checker_EXE
        path: dist/DQ_Checker.exe
